version: '3.9'

services:
  consul:
    image: webnitros/consul-client:latest
    command: >-
      agent
      -config-file=/mnt/data/consul.json
    secrets:
      - CONSUL_KV_TOKEN
      - CONSUL_KV_URL
    networks:
      - consul
    ports:
      - "9300:9300"
      - "9301:9301"
      - "9301:9301/udp"
      - "9302:9302"
      - "9302:9302/udp"
      #- "9500:9500"
      #- "9600:9600/udp"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9500/v1/agent/checks" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
  registrator:
    image: webnitros/registrator:latest
    command: -internal consul://consul:9500
    restart: always
    environment:
      CONSUL_HTTP_TOKEN_FILE: "/run/secrets/CONSUL_KV_TOKEN"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
    secrets:
      - CONSUL_KV_TOKEN
    networks:
      - consul
    links:
      - consul
    depends_on:
      - consul
    logging: # Добавляем опцию logging
      driver: "json-file"          # Используем json-file драйвер
      options:
        max-size: "10m"            # Ограничиваем размер лог-файла
        max-file: "3"              # Ограничиваем количество лог-файлов
        labels: "error"            # Только ошибки будут писаться в лог

networks:
  consul:
    external: false

secrets:
  CONSUL_KV_URL:
    file: ./consul.url
  CONSUL_KV_TOKEN:
    file: ./consul.token
