version: '3.9'

services:
    # Consul
    consul:
        image: webnitros/consul:latest
        ports:
            - "9300:9300"
            - "9500:9500"
            - "9600:9600/udp"
        environment:
            CONSUL_CONFIG_FILE: "env"
            #TYPE_SERVICE: "${TYPE_SERVICE}"
            #CONSUL_HTTP_TOKEN: "${CONSUL_HTTP_TOKEN}"
#
            ## Agent
            #JOIN_SERVER_IP: "${JOIN_SERVER_IP}"
            #AGENT_NODE_NAME: "${AGENT_NODE_NAME}"
            #AGENT_ADVERTISE_ADDR: "${AGENT_ADVERTISE_ADDR}"
#
            ## Server
            #BOOTSTRAP_EXPECT: "${BOOTSTRAP_EXPECT}"
            #SERVER_NODE_NAME: "${SERVER_NODE_NAME}"
            #SERVER_ADVERTISE_ADDR: "${SERVER_ADVERTISE_ADDR}"
        volumes:
            - consul_server1_data:/consul/data
            - consul_server1_config:/consul/config
        networks:
            - consul
        healthcheck:
            test: [ "CMD", "curl", "-f", "http://localhost:9500/v1/agent/checks" ]
            interval: 30s
            timeout: 10s
            retries: 5
            start_period: 60s

    # Registrator
    registrator:
        image: gliderlabs/registrator:master
        command: -internal consul://consul:9500
        restart: always
        environment:
            CONSUL_HTTP_TOKEN: "${CONSUL_HTTP_TOKEN}"
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock
        networks:
            - consul
        links:
            - consul
        #depends_on:
        #    - consul
        depends_on:
            consul:
                condition: service_healthy

volumes:
    consul_server1_data:
    consul_server1_config:

networks:
    consul:
        external: false

